config/routes.rb
LinkedinAuth::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  match 'protected_page' => 'home#protected_page', as: :protected_page

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, only: 'protected_page'
  before_filter :fetch_linkedin_information, only: 'index'

  # Just fetch all the linkedin for the user
  def fetch_linkedin_information
    if current_user && !current_user.linkedin_uid.blank?
      client = current_user.linkedin_client

      # Fetch the user positions
      user_positions = client.profile(:fields => %w(positions))
      LinkedinPosition.where(user_id: current_user.id).delete_all()
      if user_positions['positions']['total'].to_i > 0
        user_positions['positions']['all'].each do |position|
          if LinkedinCompany.where(linkedin_id: position['company']['id']).exists?
            company = LinkedinCompany.where(linkedin_id: position['company']['id'].to_i).first
          else
            company = LinkedinCompany.new(linkedin_id: position['company']['id'].to_i,
                                          industry: position['company']['industry'],
                                          name: position['company']['name'],
                                          company_type: position['company']['type'],
                                          ticker: position['company']['ticker'])
            company.save
          end
          position = LinkedinPosition.new(linkedin_id: position['id'].to_i,
                                          linkedin_company: company,
                                          is_current: position['is_current'],
                                          start_date: Date.strptime("#{position['start_date']['month']}/#{position['start_date']['year']}", '%m/%Y'),
                                          end_date: (Date.strptime("#{position['end_date']['month']}/#{position['end_date']['year']}", '%m/%Y') rescue nil),
                                          summary: position['summary'],
                                          title: position['title'])
          position.user_id = current_user.id
          position.save
        end
      end

      # User connections
      connections = client.connections
      if connections['total'].to_i > 0
        connections['all'].each do |connection|
          if LinkedinConnection.where(linkedin_id: connection['id']).exists?
            linkedin_connection = LinkedinConnection.where(linkedin_id: connection['id']).first
          else
            linkedin_connection = LinkedinConnection.new(linkedin_id: connection['id'])
          end
          linkedin_location = nil
          begin
            if LinkedinLocation.where(code: connection['location']['country']['code']).exists?
              linkedin_location = LinkedinLocation.where(code: connection['location']['country']['code']).first
            else
              linkedin_location = LinkedinLocation.new(code: connection['location']['country']['code'],
                                                       name: connection['location']['name'])
              linkedin_location.save
            end
          rescue Exception
          end

          linkedin_connection.linkedin_location = linkedin_location

          linkedin_connection.first_name = connection['first_name']
          linkedin_connection.last_name = connection['last_name']
          linkedin_connection.headline = connection['headline']
          linkedin_connection.industry = connection['industry']
          linkedin_connection.picture_url = connection['picture_url']
          linkedin_connection.public_profile_url = connection['site_standard_profile_request']['url'] rescue nil

          linkedin_connection.save

          linkedin_connection.users << current_user unless linkedin_connection.users.include?(current_user)
        end
      end

      # Fetch the user groups
      group_memberships = client.group_memberships
      UserGroup.where(user_id: current_user.id).delete_all()
      if group_memberships['total'].to_i > 0
        group_memberships['all'].each do |group_membership|
          if LinkedinGroup.where(linkedin_id: group_membership['group']['id']).exists?
            linkedin_group = LinkedinGroup.where(linkedin_id: group_membership['group']['id']).first
          else
            linkedin_group = LinkedinGroup.create(linkedin_id: group_membership['group']['id'],
                                               name: group_membership['group']['name'])
          end

          UserGroup.create(user: current_user,
                           linkedin_group: linkedin_group,
                           linkedin_id: group_membership['id'],
                           membership_state: group_membership['membership_state']['code'])
        end
      end


      user_educations = client.profile(:fields => %w(educations))
      LinkedinEducation.where(user_id: current_user.id).delete_all()
      if user_educations['educations']['total'].to_i > 0
        user_educations['educations']['all'].each do |education|
          LinkedinEducation.create(user: current_user,
                                   linkedin_id: education['id'].to_i,
                                   school_name: education['school_name'],
                                   field_of_study: education['field_of_study'],
                                   start_date: (Date.strptime("#{education['start_date']['month']}/#{education['start_date']['year']}", '%m/%Y') rescue nil),
                                   end_date: (Date.strptime("#{education['end_date']['month']}/#{education['end_date']['year']}", '%m/%Y') rescue nil),
                                   degree: education['degree'],
                                   activities: education['activities'],
                                   notes: education['notes'])
        end
      end
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>This is the home page</h1>

<%- if user_signed_in? %>
  <%= link_to('Access protected page', protected_page_path) %>
  <br/>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
  <br/>
  <h3>Linkedin Information</h3>
  <%- if current_user.linkedin_uid %>
    <%= image_tag(current_user.picture_url) %>
    <p>
      Linkedin ID: <%= current_user.linkedin_uid %>
      <br/>
      First Name: <%= current_user.first_name %>
      <br/>
      Last Name: <%= current_user.last_name %>
      <br/>
      Headline: <%= current_user.headline %>
      <br/>
      Industry: <%= current_user.industry %>
      <br/>
      Linkedin: <%= link_to(current_user.public_profile_url, current_user.public_profile_url) %>
      <br/>
    </p>

    <h3>Positions</h3>
    <table>
      <thead>
      <tr>
        <td>Linkedin ID</td>
        <td>Company</td>
        <td>Is Current?</td>
        <td>Start Date</td>
        <td>End Date</td>
        <td>Title</td>
        <td>Summary</td>
      </tr>
      </thead>
      <tbody>
      <%- current_user.linkedin_positions.each do |position| %>
        <tr>
          <td><%= position.linkedin_id %></td>
          <td><%= position.linkedin_company.name %></td>
          <td><%= position.is_current? %></td>
          <td><%= position.start_date %></td>
          <td><%= position.end_date %></td>
          <td><%= position.title %></td>
          <td><%= truncate(position.summary, length: 100) %></td>
        </tr>
      <%- end %>
      </tbody>
    </table>

    <h3>Companies</h3>
    <table>
      <thead>
      <tr>
        <td>Linkedin ID</td>
        <td>Name</td>
        <td>Type</td>
        <td>Industry</td>
        <td>Ticker</td>
      </tr>
      </thead>
      <tbody>
      <%- current_user.linkedin_companies.each do |company| %>
        <tr>
          <td><%= company.linkedin_id %></td>
          <td><%= company.name %></td>
          <td><%= company.company_type %></td>
          <td><%= company.industry %></td>
          <td><%= company.ticker %></td>
        </tr>
      <%- end %>
      </tbody>
    </table>

    <h3>Groups</h3>
    <table>
      <thead>
      <tr>
        <td>Linkedin ID</td>
        <td>Name</td>
        <td>Membership State</td>
      </tr>
      </thead>
      <tbody>
      <%- current_user.user_groups.each do |user_group| %>
        <tr>
          <td><%= user_group.linkedin_group.linkedin_id %></td>
          <td><%= user_group.linkedin_group.name %></td>
          <td><%= user_group.membership_state %></td>
        </tr>
      <%- end %>
      </tbody>
    </table>

    <h3>Education</h3>
    <table>
      <thead>
      <tr>
        <td>Linkedin ID</td>
        <td>School Name</td>
        <td>Field Of Study</td>
        <td>Start Date</td>
        <td>End Date</td>
        <td>Degree</td>
        <td>Activities</td>
        <td>Notes</td>
      </tr>
      </thead>
      <tbody>
      <%- current_user.linkedin_educations.each do |education| %>
        <tr>
          <td><%= education.linkedin_id %></td>
          <td><%= education.school_name %></td>
          <td><%= education.field_of_study %></td>
          <td><%= education.start_date %></td>
          <td><%= education.end_date %></td>
          <td><%= education.degree %></td>
          <td><%= education.activities %></td>
          <td><%= education.notes %></td>
        </tr>
      <%- end %>
      </tbody>
    </table>

  <%- else %>
    <%= link_to('Link my LinkedIn Account', user_omniauth_authorize_path('linkedin')) %>
  <%- end %>
<%- else %>
  <%= link_to("Sign in with LinkedIn", user_omniauth_authorize_path('linkedin')) %>
  <br/>
  <%= link_to('Register', new_user_registration_path) %>
  <br/>
  <%= link_to('Login', new_user_session_path) %>
  <br/>
  <%= link_to('Access protected page', protected_page_path) %>
<%- end %>

app/views/home/protected_page.html.erb
This is a protected page
<br/>
<%= link_to('Go back to index page', root_path) %>